version: '3.8'

services:
  app:
    build: .
    container_name: secret-web
    ports:
      - "5063:3000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: secret-admin
    ports:
      - "5064:3000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
      - ADMIN_PASSWORD=hwFgxC$)k9APtbQN
